env:
  browser: true
  node: true
  jest: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parser: "@babel/eslint-parser"
parserOptions:
  ecmaVersion: 6
  sourceType: module
settings:
  react:
    version: detect
rules:
  no-console: 1
